import OpenAI from "openai"

import { calculateApiCostOpenAI } from "@shared/api/cost"

import type { ModelInfo } from "@jabberwock/types"

import type { ApiStreamUsageChunk } from "@api/transform/stream"

import type { CacheableTextContent, LiteLLMUsage } from "./types"

/**
 * Detect if the model is a Gemini model that requires thought signature handling.
 * Gemini 3 models validate thought signatures for tool/function calling steps.
 */
export function isGeminiModel(modelId: string): boolean {
	// Match various Gemini model patterns:
	// - gemini-3-pro, gemini-3-flash, gemini-3-*
	// - gemini 3 pro, Gemini 3 Pro (space-separated, case-insensitive)
	// - gemini/gemini-3-*, google/gemini-3-*
	// - vertex_ai/gemini-3-*, vertex/gemini-3-*
	// Also match Gemini 2.5+ models which use similar validation
	const lowerModelId = modelId.toLowerCase()
	return (
		// Match hyphenated versions: gemini-3, gemini-2.5
		lowerModelId.includes("gemini-3") ||
		lowerModelId.includes("gemini-2.5") ||
		// Match space-separated versions: "gemini 3", "gemini 2.5"
		// This handles model names like "Gemini 3 Pro" from LiteLLM model groups
		lowerModelId.includes("gemini 3") ||
		lowerModelId.includes("gemini 2.5") ||
		// Also match provider-prefixed versions
		/\b(gemini|google|vertex_ai|vertex)\/gemini[-\s](3|2\.5)/i.test(modelId)
	)
}

/**
 * Inject thought signatures for Gemini models via provider_specific_fields.
 * This is required when switching from other models to Gemini to satisfy API validation
 * for function calls that weren't generated by Gemini (and thus lack thought signatures).
 *
 * Per LiteLLM documentation:
 * - Thought signatures are stored in provider_specific_fields.thought_signature of tool calls
 * - The dummy signature base64("skip_thought_signature_validator") bypasses validation
 *
 * We inject the dummy signature on EVERY tool call unconditionally to ensure Gemini
 * doesn't complain about missing/corrupted signatures when conversation history
 * contains tool calls from other models (like Claude).
 */
export function injectThoughtSignatureForGemini(
	openAiMessages: OpenAI.Chat.ChatCompletionMessageParam[],
): OpenAI.Chat.ChatCompletionMessageParam[] {
	// Base64 encoded "skip_thought_signature_validator" as per LiteLLM docs
	const dummySignature = Buffer.from("skip_thought_signature_validator").toString("base64")

	return openAiMessages.map((msg) => {
		if (msg.role === "assistant") {
			const toolCalls = (msg as OpenAI.Chat.ChatCompletionAssistantMessageParam).tool_calls

			// Only process if there are tool calls
			if (toolCalls && toolCalls.length > 0) {
				// Inject dummy signature into ALL tool calls' provider_specific_fields
				// This ensures Gemini doesn't reject tool calls from other models
				const updatedToolCalls = toolCalls.map((tc) => {
					const tcExt = tc as { provider_specific_fields?: Record<string, unknown> }
					return {
						...tc,
						provider_specific_fields: {
							...(tcExt.provider_specific_fields || {}),
							thought_signature: dummySignature,
						},
					}
				})

				return {
					...msg,
					tool_calls: updatedToolCalls,
				}
			}
		}
		return msg
	})
}

export function applyCacheControlToMessage(
	message: OpenAI.Chat.ChatCompletionMessageParam,
): OpenAI.Chat.ChatCompletionMessageParam {
	if (message.role === "function") {
		return message
	}

	if (typeof message.content === "string") {
		return {
			...message,
			content: [
				{
					type: "text",
					text: message.content,
					cache_control: { type: "ephemeral" },
				} as CacheableTextContent,
			] as OpenAI.Chat.ChatCompletionContentPartText[],
		}
	}

	if (Array.isArray(message.content) && message.content.length > 0) {
		const msgContent = message.content
		return {
			...message,
			content: msgContent.map((content, contentIndex) =>
				contentIndex === msgContent.length - 1
					? ({ ...content, cache_control: { type: "ephemeral" as const } } as CacheableTextContent)
					: content,
			) as OpenAI.Chat.ChatCompletionContentPartText[],
		}
	}

	return message
}

export function* processLiteLLMChunk(
	delta: OpenAI.Chat.Completions.ChatCompletionChunk.Choice.Delta | undefined,
): Generator<
	| { type: "text"; text: string }
	| { type: "tool_call_partial"; index: number; id?: string; name?: string; arguments?: string }
> {
	if (delta?.content) {
		yield { type: "text", text: delta.content }
	}

	if (delta?.tool_calls) {
		for (const toolCall of delta.tool_calls) {
			yield {
				type: "tool_call_partial",
				index: toolCall.index,
				id: toolCall.id,
				name: toolCall.function?.name,
				arguments: toolCall.function?.arguments,
			}
		}
	}
}

export function getCacheTokens(usage: LiteLLMUsage): { cacheWriteTokens: number; cacheReadTokens: number } {
	const cacheWriteTokens = usage.cache_creation_input_tokens || usage.prompt_cache_miss_tokens || 0
	const cacheReadTokens =
		usage.prompt_tokens_details?.cached_tokens ||
		usage.cache_read_input_tokens ||
		usage.prompt_cache_hit_tokens ||
		0
	return { cacheWriteTokens, cacheReadTokens }
}

export function buildUsageChunk(lastUsage: LiteLLMUsage, info: ModelInfo): ApiStreamUsageChunk {
	const { cacheWriteTokens, cacheReadTokens } = getCacheTokens(lastUsage)

	const { totalCost } = calculateApiCostOpenAI(
		info,
		lastUsage.prompt_tokens || 0,
		lastUsage.completion_tokens || 0,
		cacheWriteTokens,
		cacheReadTokens,
	)

	return {
		type: "usage",
		inputTokens: lastUsage.prompt_tokens || 0,
		outputTokens: lastUsage.completion_tokens || 0,
		cacheWriteTokens: cacheWriteTokens > 0 ? cacheWriteTokens : undefined,
		cacheReadTokens: cacheReadTokens > 0 ? cacheReadTokens : undefined,
		totalCost,
	}
}
