import { ORGANIZATION_ALLOW_ALL } from "@jabberwock/types"
import { defaultModeSlug } from "@shared/modes"
import { defaultPrompts } from "@shared/modes"
import { experimentDefault } from "@shared/experiments"

export const extStateDefaults = {
	apiConfiguration: {},
	version: "",
	messages: [],
	taskHistory: [],
	shouldShowAnnouncement: false,
	allowedCommands: [],
	deniedCommands: [],
	soundEnabled: false,
	soundVolume: 0.5,
	ttsEnabled: false,
	ttsSpeed: 1,
	enableCheckpoints: true,
	checkpointTimeout: 15,
	language: "en",
	writeDelayMs: 1000,
	terminalShellIntegrationTimeout: 4000,
	mcpEnabled: true,
	taskSyncEnabled: false,
	currentApiConfigName: "default",
	listApiConfigMeta: [],
	mode: defaultModeSlug,
	customModePrompts: defaultPrompts,
	customSupportPrompts: {},
	experiments: experimentDefault,
	enhancementApiConfigId: "",
	hasOpenedModeSelector: false,
	autoApprovalEnabled: false,
	customModes: [],
	maxOpenTabsContext: 20,
	maxWorkspaceFiles: 200,
	cwd: "",
	telemetrySetting: "unset" as const,
	showJabberwockIgnoredFiles: true,
	enableSubfolderRules: false,
	renderContext: "sidebar",
	maxReadFileLine: -1,
	maxImageFileSize: 5,
	maxTotalImageSize: 20,
	pinnedApiConfigs: {},
	terminalZshOhMy: false,
	terminalZshP10k: false,
	terminalZdotdir: false,
	historyPreviewCollapsed: false,
	reasoningBlockCollapsed: true,
	enterBehavior: "send",
	cloudUserInfo: null,
	cloudIsAuthenticated: false,
	cloudOrganizations: [],
	sharingEnabled: false,
	publicSharingEnabled: false,
	organizationAllowList: ORGANIZATION_ALLOW_ALL,
	organizationSettingsVersion: -1,
	autoCondenseContext: true,
	autoCondenseContextPercent: 100,
	profileThresholds: {},
	locatorTarget: "code",
	codebaseIndexConfig: {
		codebaseIndexEnabled: true,
		codebaseIndexQdrantUrl: "http://localhost:6333",
		codebaseIndexEmbedderProvider: "openai",
		codebaseIndexEmbedderBaseUrl: "",
		codebaseIndexEmbedderModelId: "",
		codebaseIndexSearchMaxResults: undefined,
		codebaseIndexSearchMinScore: undefined,
	},
	codebaseIndexModels: { ollama: {}, openai: {} },
	includeDiagnosticMessages: true,
	maxDiagnosticMessages: 50,
	openRouterImageApiKey: "",
	openRouterImageGenerationSelectedModel: "",
	includeCurrentTime: true,
	includeCurrentCost: true,
	lockApiConfigAcrossModes: false,
	devtoolEnabled: false,
}
