export type FireworksModelId =
	| "accounts/fireworks/models/kimi-k2-instruct"
	| "accounts/fireworks/models/kimi-k2-instruct-0905"
	| "accounts/fireworks/models/kimi-k2-thinking"
	| "accounts/fireworks/models/kimi-k2p5"
	| "accounts/fireworks/models/minimax-m2"
	| "accounts/fireworks/models/minimax-m2p1"
	| "accounts/fireworks/models/qwen3-235b-a22b-instruct-2507"
	| "accounts/fireworks/models/qwen3-coder-480b-a35b-instruct"
	| "accounts/fireworks/models/deepseek-r1-0528"
	| "accounts/fireworks/models/deepseek-v3"
	| "accounts/fireworks/models/deepseek-v3p1"
	| "accounts/fireworks/models/deepseek-v3p2"
	| "accounts/fireworks/models/glm-4p5"
	| "accounts/fireworks/models/glm-4p5-air"
	| "accounts/fireworks/models/glm-4p6"
	| "accounts/fireworks/models/glm-4p7"
	| "accounts/fireworks/models/gpt-oss-20b"
	| "accounts/fireworks/models/gpt-oss-120b"
	| "accounts/fireworks/models/llama-v3p3-70b-instruct"
	| "accounts/fireworks/models/llama4-maverick-instruct-basic"
	| "accounts/fireworks/models/llama4-scout-instruct-basic"

export const fireworksDefaultModelId: FireworksModelId = "accounts/fireworks/models/kimi-k2-instruct-0905"
