import React from "react"
import { HeaderSection } from "../sections/header-section"
import { ConfigSection } from "../sections/config-section"
import { GlobalSection } from "../sections/global-section"
import { Section } from "@src/features/settings/components/shared/Section"
import { ModesViewDialogs } from "./ModesViewDialogs"
import type { ModesViewLayoutProps } from "./types"

export const ModesViewLayout: React.FC<ModesViewLayoutProps> = ({
	t,
	visualMode,
	displayModes,
	searchValue,
	open,
	isRenamingMode,
	renameInputValue,
	isExporting,
	isImporting,
	isCreateModeDialogOpen,
	isDialogOpen,
	showImportDialog,
	showDeleteConfirm,
	showConfigMenu,
	isToolsEditMode,
	isCustomMode,
	currentModeName,
	currentModeSlug,
	currentMode,
	customModes,
	customModePrompts,
	customInstructions,
	listApiConfigMeta,
	currentApiConfigName,
	selectedPromptTitle,
	selectedPromptContent,
	newModeName,
	newModeSlug,
	newModeDescription,
	newModeRoleDefinition,
	newModeWhenToUse,
	newModeCustomInstructions,
	newModeGroups,
	newModeSource,
	nameError,
	slugError,
	descriptionError,
	roleDefinitionError,
	groupsError,
	importLevel,
	modeToDelete,
	onOpenChange,
	onSearchChange,
	onClearSearch,
	onModeSelect,
	onStartRename,
	onSaveRename,
	onCancelRename,
	onRenameInputChange,
	onCreateMode,
	onDeleteMode,
	onExport,
	getCurrentMode,
	setShowConfigMenu,
	setShowImportDialog,
	setIsCreateModeDialogOpen,
	setIsDialogOpen,
	setIsToolsEditMode,
	setIsImporting,
	setImportLevel,
	setShowDeleteConfirm,
	setModeToDelete,
	handleRoleDefinitionChange,
	handleDescriptionChange,
	handleWhenToUseChange,
	handleCustomInstructionsChange,
	handleAgentReset,
	handleGroupChangeForTool,
	handleCreateMode,
	handleNameChange,
	handleNewModeGroupToggle,
	getRoleDefinitionVal,
	getDescriptionVal,
	getWhenToUseVal,
	getCustomInstructionsVal,
	onSlugChange,
	onDescriptionChange,
	onRoleDefinitionChange,
	onWhenToUseChange,
	onCustomInstructionsChange,
	onSourceChange,
}) => {
	return (
		<div>
			<Section>
				<HeaderSection
					displayModes={displayModes}
					searchValue={searchValue}
					open={open}
					isRenamingMode={isRenamingMode}
					renameInputValue={renameInputValue}
					isExporting={isExporting}
					isImporting={isImporting}
					showConfigMenu={showConfigMenu}
					currentApiConfigName={currentApiConfigName}
					listApiConfigMeta={listApiConfigMeta}
					onOpenChange={onOpenChange}
					onSearchChange={onSearchChange}
					onClearSearch={onClearSearch}
					onModeSelect={onModeSelect}
					onStartRename={onStartRename}
					onSaveRename={onSaveRename}
					onCancelRename={onCancelRename}
					onRenameInputChange={onRenameInputChange}
					onCreateMode={onCreateMode}
					onDeleteMode={onDeleteMode}
					onExport={onExport}
					getCurrentMode={getCurrentMode}
					setShowConfigMenu={setShowConfigMenu}
					setShowImportDialog={setShowImportDialog}
					setIsCreateModeDialogOpen={setIsCreateModeDialogOpen}
				/>
				<ConfigSection
					visualMode={visualMode}
					customModes={customModes}
					isToolsEditMode={isToolsEditMode}
					isCustomMode={isCustomMode}
					currentMode={currentMode}
					currentModeName={currentModeName}
					currentModeSlug={currentModeSlug}
					customModePrompts={customModePrompts}
					handleRoleDefinitionChange={handleRoleDefinitionChange}
					handleDescriptionChange={handleDescriptionChange}
					handleWhenToUseChange={handleWhenToUseChange}
					handleCustomInstructionsChange={handleCustomInstructionsChange}
					handleAgentReset={handleAgentReset}
					handleGroupChangeForTool={handleGroupChangeForTool}
					getCurrentMode={getCurrentMode}
					getRoleDefinitionVal={getRoleDefinitionVal}
					getDescriptionVal={getDescriptionVal}
					getWhenToUseVal={getWhenToUseVal}
					getCustomInstructionsVal={getCustomInstructionsVal}
					setIsToolsEditMode={setIsToolsEditMode}
				/>
				<GlobalSection customInstructions={customInstructions} />
			</Section>
			<ModesViewDialogs
				isCreateModeDialogOpen={isCreateModeDialogOpen}
				setIsCreateModeDialogOpen={setIsCreateModeDialogOpen}
				isDialogOpen={isDialogOpen}
				setIsDialogOpen={setIsDialogOpen}
				showImportDialog={showImportDialog}
				setShowImportDialog={setShowImportDialog}
				showDeleteConfirm={showDeleteConfirm}
				setShowDeleteConfirm={setShowDeleteConfirm}
				setModeToDelete={setModeToDelete}
				isImporting={isImporting}
				setIsImporting={setIsImporting}
				importLevel={importLevel}
				setImportLevel={setImportLevel}
				modeToDelete={modeToDelete}
				selectedPromptTitle={selectedPromptTitle}
				selectedPromptContent={selectedPromptContent}
				currentModeName={currentModeName}
				newModeName={newModeName}
				newModeSlug={newModeSlug}
				newModeDescription={newModeDescription}
				newModeRoleDefinition={newModeRoleDefinition}
				newModeWhenToUse={newModeWhenToUse}
				newModeCustomInstructions={newModeCustomInstructions}
				newModeGroups={newModeGroups}
				newModeSource={newModeSource}
				nameError={nameError}
				slugError={slugError}
				descriptionError={descriptionError}
				roleDefinitionError={roleDefinitionError}
				groupsError={groupsError}
				onNameChange={handleNameChange}
				onSlugChange={onSlugChange}
				onDescriptionChange={onDescriptionChange}
				onRoleDefinitionChange={onRoleDefinitionChange}
				onWhenToUseChange={onWhenToUseChange}
				onCustomInstructionsChange={onCustomInstructionsChange}
				onSourceChange={onSourceChange}
				onGroupToggle={handleNewModeGroupToggle}
				onCreate={handleCreateMode}
				t={t}
			/>
		</div>
	)
}
