export { csharpQuery, cQuery, cppQuery, cssQuery } from "./a-d"
export { elispQuery, elixirQuery, embeddedTemplateQuery, goQuery, htmlQuery } from "./e-h"
export { javaQuery, javascriptQuery, kotlinQuery, luaQuery } from "./j-l"
export { ocamlQuery, phpQuery, pythonQuery, rubyQuery, rustQuery } from "./o-r"
export { scalaQuery, solidityQuery, swiftQuery, systemrdlQuery } from "./s"
export { tlaPlusQuery, tomlQuery, tsxQuery, typescriptQuery, vueQuery, zigQuery } from "./t-z"
