export { registerGlobalErrorHandlers, nextRequestId } from "./factory-helpers.js"
export type { DevtoolBridgeProvider } from "./factory-helpers.js"
export { handleGetConsole, handleSearchConsole } from "./factory-console.js"
export { createDomBridgeMethods } from "./factory-dom.js"
export { createStateMethods } from "./factory-state.js"
export { createMockBridge } from "./factory-mock.js"
