/**
 * Foundation feature — event type constants.
 */
export const foundationEventConstants = {
	// ─── Agent State (Webview → Backend) ───────────────────────────
	CURRENT_API_CONFIG_NAME: "currentApiConfigName" as const,
	SAVE_API_CONFIGURATION: "saveApiConfiguration" as const,
	UPSERT_API_CONFIGURATION: "upsertApiConfiguration" as const,
	DELETE_API_CONFIGURATION: "deleteApiConfiguration" as const,
	LOAD_API_CONFIGURATION: "loadApiConfiguration" as const,
	LOAD_API_CONFIGURATION_BY_ID: "loadApiConfigurationById" as const,
	RENAME_API_CONFIGURATION: "renameApiConfiguration" as const,
	GET_LIST_API_CONFIGURATION: "getListApiConfiguration" as const,
	CUSTOM_INSTRUCTIONS: "customInstructions" as const,
	FLUSH_ROUTER_MODELS: "flushRouterModels" as const,
	REQUEST_ROUTER_MODELS: "requestRouterModels" as const,
	REQUEST_OPEN_AI_MODELS: "requestOpenAiModels" as const,
	REQUEST_OLLAMA_MODELS: "requestOllamaModels" as const,
	REQUEST_LM_STUDIO_MODELS: "requestLmStudioModels" as const,
	REQUEST_ROO_MODELS: "requestRooModels" as const,
	REQUEST_ROO_CREDIT_BALANCE: "requestRooCreditBalance" as const,
	REQUEST_VS_CODE_LM_MODELS: "requestVsCodeLmModels" as const,
	UPDATE_VS_CODE_SETTING: "updateVSCodeSetting" as const,
	GET_VS_CODE_SETTING: "getVSCodeSetting" as const,
	VS_CODE_SETTING: "vsCodeSetting" as const,
	UPDATE_PROMPT: "updatePrompt" as const,
	GET_SYSTEM_PROMPT: "getSystemPrompt" as const,
	COPY_SYSTEM_PROMPT: "copySystemPrompt" as const,
	SYSTEM_PROMPT: "systemPrompt" as const,
	AUTO_APPROVAL_ENABLED: "autoApprovalEnabled" as const,
	UPDATE_CUSTOM_MODE: "updateCustomMode" as const,
	DELETE_CUSTOM_MODE: "deleteCustomMode" as const,
	EXPORT_MODE: "exportMode" as const,
	IMPORT_MODE: "importMode" as const,
	CHECK_RULES_DIRECTORY: "checkRulesDirectory" as const,
	SET_OPEN_AI_CUSTOM_MODEL_INFO: "setopenAiCustomModelInfo" as const,
	OPEN_CUSTOM_MODES_SETTINGS: "openCustomModesSettings" as const,
	CODEBASE_INDEX_ENABLED: "codebaseIndexEnabled" as const,
	REQUEST_INDEXING_STATUS: "requestIndexingStatus" as const,
	START_INDEXING: "startIndexing" as const,
	STOP_INDEXING: "stopIndexing" as const,
	CLEAR_INDEX_DATA: "clearIndexData" as const,
	INDEXING_STATUS_UPDATE: "indexingStatusUpdate" as const,
	INDEX_CLEARED: "indexCleared" as const,
	TOGGLE_WORKSPACE_INDEXING: "toggleWorkspaceIndexing" as const,
	SET_AUTO_ENABLE_DEFAULT: "setAutoEnableDefault" as const,
	SAVE_CODE_INDEX_SETTINGS_ATOMIC: "saveCodeIndexSettingsAtomic" as const,
	REQUEST_CODE_INDEX_SECRET_STATUS: "requestCodeIndexSecretStatus" as const,
	HAS_OPENED_MODE_SELECTOR: "hasOpenedModeSelector" as const,
	LOCK_API_CONFIG_ACROSS_MODES: "lockApiConfigAcrossModes" as const,
	UPDATE_SYSTEM_PROMPT_TEMPLATE: "updateSystemPromptTemplate" as const,
	UPDATE_CONDENSING_PROMPT: "updateCondensingPrompt" as const,
	ENHANCEMENT_API_CONFIG_ID: "enhancementApiConfigId" as const,
	DEBUG_SETTING: "debugSetting" as const,

	// ─── Agent State (Backend → Webview) ───────────────────────────
	LIST_API_CONFIG: "listApiConfig" as const,
	ROUTER_MODELS: "routerModels" as const,
	OPEN_AI_MODELS: "openAiModels" as const,
	OLLAMA_MODELS: "ollamaModels" as const,
	LM_STUDIO_MODELS: "lmStudioModels" as const,
	VS_CODE_LM_MODELS: "vsCodeLmModels" as const,
	VS_CODE_LM_API_AVAILABLE: "vsCodeLmApiAvailable" as const,
	SINGLE_ROUTER_MODEL_FETCH_RESPONSE: "singleRouterModelFetchResponse" as const,
	DELETE_CUSTOM_MODE_CHECK: "deleteCustomModeCheck" as const,
	EXPORT_MODE_RESULT: "exportModeResult" as const,
	IMPORT_MODE_RESULT: "importModeResult" as const,
	CHECK_RULES_DIRECTORY_RESULT: "checkRulesDirectoryResult" as const,
	CODEBASE_INDEX_CONFIG: "codebaseIndexConfig" as const,
	CODE_INDEX_SETTINGS_SAVED: "codeIndexSettingsSaved" as const,
	CODE_INDEX_SECRET_STATUS: "codeIndexSecretStatus" as const,

	// ─── MST (Foundation) ──────────────────────────────────────────
	MST_PATCH: "mstPatch" as const,
	MST_SNAPSHOT_BATCH: "mstSnapshotBatch" as const,
} as const

export type FoundationEventKey = (typeof foundationEventConstants)[keyof typeof foundationEventConstants]
