/**
 * MACHINE-GENERATED import-ban debt.
 *
 * Both lists are DERIVED from the actual source tree by `scripts/gen-import-debt.mjs`. They exist
 * because two bans use core ESLint `no-restricted-imports` (which cannot use the generic rule
 * ledger), and a hand-maintained list of paths in a rule is precisely what we are removing: it
 * stops matching as soon as the code moves. Regenerate with `pnpm import-debt`; the ledger guard
 * fails the build if either list GROWS.
 */

/**
 * Files in @jabberwock/types that still import zod (v3 plan B6).
 * Generated by scripts/gen-import-debt.mjs — do not edit. Only shrinks.
 *
 * @type {string[]}
 */
export const zodDebt = [
	"src/api/ipc.ts",
	"src/cloud/organization.ts",
	"src/cloud/schemas.ts",
	"src/cloud/socket.ts",
	"src/events/task.ts",
	"src/events/types.ts",
	"src/execution/codebase-index.ts",
	"src/execution/terminal.ts",
	"src/features/cli.ts",
	"src/features/experiment.ts",
	"src/features/marketplace.ts",
	"src/mcp/server-config.ts",
	"src/messages/notification.ts",
	"src/messages/types.ts",
	"src/models/mode.ts",
	"src/models/model-main.ts",
	"src/payload-schemas.ts",
	"src/providers/single/j-o/jabberwock.ts",
	"src/settings/global/schema.ts",
	"src/settings/provider/categories.ts",
	"src/settings/provider/schemas.ts",
	"src/settings/provider/settings.ts",
	"src/task/followup.ts",
	"src/task/history.ts",
	"src/task/provider.ts",
	"src/telemetry/event-schema.ts",
	"src/telemetry/properties.ts",
	"src/todo.ts",
	"src/tool/definitions.ts",
	"src/vscode/types.ts",
]

/**
 * Backend app-layer files (actions/handlers/events) that still import an LLM SDK (v4 §1.3a).
 * Generated by scripts/gen-import-debt.mjs — do not edit. Only shrinks.
 *
 * @type {string[]}
 */
export const providerSdkDebt = [
	"features/api/handlers/request/prepare/attemptApiRequest.ts",
	"features/api/handlers/request/prepare/helpers.ts",
	"features/api/handlers/request/prepare/main.ts",
	"features/api/handlers/request/prepare/mergeConsecutiveApiMessages.ts",
	"features/api/handlers/request/process/streaming.ts",
	"features/chat/task/actions/resumeTask/from-history.ts",
	"features/chat/task/actions/resumeTask/helpers.ts",
	"features/chat/task/actions/resumeTask/rebuild.ts",
	"features/chat/task/messages/actions/presentAssistantMessage/helpers.ts",
	"features/chat/task/messages/actions/save/blocks.ts",
	"features/chat/task/messages/actions/save/io.ts",
	"features/chat/task/messages/actions/save/transform.ts",
	"features/chat/task/messages/actions/save/types.ts",
	"features/chat/task/messages/handlers/user/on-message-received.ts",
	"features/chat/tools/actions/buildToolDefinitions.ts",
	"features/chat/tools/actions/executeTools.ts",
	"features/chat/tools/actions/flushPendingToolResults.ts",
	"features/chat/tools/actions/toolExecutor/api.ts",
	"features/chat/tools/actions/toolExecutor/execution.ts",
	"features/chat/tools/actions/toolExecutor/history.ts",
	"features/chat/tools/actions/validateToolResultIds.ts",
]
